# Generated by Django 4.1.2 on 2022-11-09 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(max_length=30)),
                ('ornament', models.CharField(max_length=100)),
                ('purity', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=60)),
                ('grossw', models.CharField(db_column='grossW', max_length=100)),
                ('stonew', models.CharField(db_column='stoneW', max_length=120)),
                ('makingc', models.CharField(db_column='makingC', max_length=120)),
                ('wastagec', models.CharField(db_column='wastageC', max_length=120)),
                ('stonec', models.CharField(db_column='stoneC', max_length=150)),
                ('netw', models.CharField(db_column='netW', max_length=120)),
                ('neta', models.CharField(db_column='NetA', max_length=160)),
                ('totala', models.CharField(db_column='totalA', max_length=160)),
                ('vaildd', models.CharField(db_column='vaildD', max_length=100)),
                ('qty', models.CharField(max_length=120)),
                ('vendor', models.CharField(max_length=180)),
                ('submitdate', models.CharField(db_column='submitDate', max_length=100)),
                ('image', models.CharField(blank=True, max_length=320, null=True)),
                ('status', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'noti',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=150)),
                ('ornament', models.CharField(max_length=150)),
                ('model1', models.CharField(max_length=255)),
                ('model2', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('pic1', models.CharField(max_length=255)),
                ('pic2', models.CharField(max_length=255)),
                ('pic3', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pics2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=150)),
                ('ornament', models.CharField(max_length=150)),
                ('model1', models.ImageField(null=True, upload_to='images_uploaded')),
                ('model2', models.ImageField(null=True, upload_to='images_uploaded')),
                ('video', models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('pic1', models.ImageField(null=True, upload_to='images_uploaded')),
                ('pic2', models.ImageField(null=True, upload_to='images_uploaded')),
                ('pic3', models.ImageField(null=True, upload_to='images_uploaded')),
                ('time', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pics2',
                'managed': True,
            },
        ),
    ]
