# Generated by Django 4.1.2 on 2022-11-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='product_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
