# Generated by Django 4.1.3 on 2022-11-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='makingcamt',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noti',
            name='wastagecamt',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
