# Generated by Django 4.1.2 on 2022-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
