# Generated by Django 4.1.2 on 2022-11-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pics',
            name='photographer_id',
            field=models.CharField(default=13, max_length=50),
            preserve_default=False,
        ),
    ]
