# Generated by Django 4.1.2 on 2022-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pics_photographer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pics2',
            name='photographer_id',
            field=models.CharField(default=13, max_length=50),
            preserve_default=False,
        ),
    ]
