# Generated by Django 4.1.2 on 2022-11-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_pics_pics2_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='vendor_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
