# Generated by Django 4.1.2 on 2022-11-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_noti_vendor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.CharField(max_length=150)),
                ('rate', models.CharField(max_length=150)),
                ('vendor', models.CharField(max_length=150)),
                ('vendor_id', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gold',
                'managed': True,
            },
        ),
    ]
