# Generated by Django 4.1.2 on 2022-11-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='makingcamt',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noti',
            name='wastagecamt',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
