# Generated by Django 4.1.2 on 2022-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_noti_makingcamt_noti_wastagecamt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_mark', models.CharField(max_length=150)),
                ('net_weight', models.CharField(max_length=150)),
                ('gross_weight', models.CharField(max_length=150)),
                ('hall_mark_print', models.CharField(max_length=150)),
                ('pack_916', models.CharField(max_length=150)),
                ('product_id', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'gold_detail',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='companyname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
