# Generated by Django 4.1.2 on 2022-10-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_metal', models.CharField(choices=[('', '-------'), ('Gold', 'Gold'), ('Silver', 'Silver')], default='Select', max_length=15)),
                ('ornament_type', models.CharField(choices=[('tikkas', 'tikkas'), ('earrings', 'earrings'), ('anklets', 'anklets'), ('bangles', 'bangles'), ('rings', 'rings'), ('necklaces', 'necklaces'), ('pendants', 'pendants'), ('toe rings', 'toe rings'), ('bracelets', 'bracelets'), ('nose pins', 'nose pins')], default='Select', max_length=15)),
                ('purity', models.IntegerField(default=0)),
            ],
        ),
    ]
