# Generated by Django 4.1.2 on 2022-10-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ornament_type',
            field=models.CharField(choices=[('', ''), ('tikkas', 'tikkas'), ('earrings', 'earrings'), ('anklets', 'anklets'), ('bangles', 'bangles'), ('rings', 'rings'), ('necklaces', 'necklaces'), ('pendants', 'pendants'), ('toe rings', 'toe rings'), ('bracelets', 'bracelets'), ('nose pins', 'nose pins')], default='Select', max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='purity',
            field=models.IntegerField(),
        ),
    ]
