# Generated by Django 4.1.2 on 2022-10-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_account_purity'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='purity',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=5),
        ),
    ]
