# Generated by Django 4.1.3 on 2022-11-29 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='login',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
