# Generated by Django 4.1.3 on 2022-11-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0002_alter_worklog_date_alter_worklog_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='login',
            field=models.TimeField(default='06:28:56'),
        ),
    ]
