# Generated by Django 4.1.3 on 2022-12-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0003_alter_worklog_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='login',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
