# Generated by Django 4.1.3 on 2022-12-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0004_alter_worklog_date_alter_worklog_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='authenticated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='comment',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sites',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
