# Generated by Django 4.1.3 on 2022-12-05 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logins', '0005_alter_sites_authenticated_alter_sites_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('comment', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
