# Generated by Django 4.1.3 on 2022-12-05 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0007_alter_assignedsite_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='assigned_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logins.assignedsite'),
        ),
    ]
