# Generated by Django 4.1.3 on 2022-12-05 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logins', '0008_sites_assigned_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='assigned_site',
        ),
        migrations.AddField(
            model_name='assignedsite',
            name='visit_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visit_assigned_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
