# Generated by Django 4.1.3 on 2022-12-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0009_remove_sites_assigned_site_assignedsite_visit_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='visit_assign_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logins.assignedsite'),
        ),
    ]
