# Generated by Django 4.1.3 on 2022-12-06 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0012_remove_sites_visit_assign_id_assignedsite_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='visit_assign_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logins.assignedsite'),
        ),
    ]
