# Generated by Django 4.1.3 on 2022-12-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0013_sites_visit_assign_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='authenticated',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='otp',
        ),
    ]
