# Generated by Django 4.1.3 on 2022-12-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0014_remove_sites_authenticated_remove_sites_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedsite',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
