# Generated by Django 4.1.3 on 2022-12-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0017_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(blank=True, null=True)),
                ('app', models.FileField(upload_to='apk/')),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
